
class AnsiFore:
    BLACK: str = ...
    RED: str = ...
    GREEN: str = ...
    YELLOW: str = ...
    BLUE: str = ...
    MAGENTA: str = ...
    CYAN: str = ...
    WHITE: str = ...
    RESET: str = ...
    LIGHTBLACK_EX: str = ...
    LIGHTRED_EX: str = ...
    LIGHTGREEN_EX: str = ...
    LIGHTYELLOW_EX: str = ...
    LIGHTBLUE_EX: str = ...
    LIGHTMAGENTA_EX: str = ...
    LIGHTCYAN_EX: str = ...
    LIGHTWHITE_EX: str = ...


class AnsiStyle:
    BRIGHT: str = ...
    DIM: str = ...
    NORMAL: str = ...
    RESET_ALL: str = ...

Fore: AnsiFore
Style: AnsiStyle
